### ISSUE TITLE
Windows Error?

### ISSUE THREAD

**Issue by apfelestrudel** [interceptic/SlayerAIO#2]
Logged in!
Ignoring exception in command start:
Traceback (most recent call last):
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\core.py", line 131, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "C:\Users\vinni\Desktop\SlayerAIO-main\SlayerAIO-main\bot.py", line 196, in start
    await process_handler(username, on=True)
  File "C:\Users\vinni\Desktop\SlayerAIO-main\SlayerAIO-main\process.py", line 89, in process_handler
    dictionary[ign] = process
                      ^^^^^^^
UnboundLocalError: cannot access local variable 'process' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\core.py", line 376, in invoke
    await injected(ctx)
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\core.py", line 139, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: UnboundLocalError: cannot access local variable 'process' where it is not associated with a value

https://i.e-z.host/pro/1gaona1c.png

**Comment by interceptic** [comment]
Found the issue patching now

**Comment by interceptic** [comment]
NVM there isnt an issue you just didnt properly put in the required files into the Slayer dir
